# Generated by Django 4.1.1 on 2023-07-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.IntegerField()),
                ('Patient_Age', models.IntegerField()),
                ('Patient_Gender', models.IntegerField()),
                ('Patient_Blood_Pressure', models.IntegerField()),
                ('Patient_Heartrate', models.IntegerField()),
                ('Heart_Disease', models.CharField(max_length=30)),
            ],
        ),
    ]
